name: CI

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      #https://github.com/docker/build-push-action/issues/281#issuecomment-766168048
      # By default, this action uses the Git context so you don't need to use the actions/checkout action to checkout the repository
      # because this will be done directly by buildkit. The git reference will be based on the event that triggered your workflow
      # and will result in the following context: https://github.com/<owner>/<repo>.git#<ref>.
      -
        name: Checkout
        uses: actions/checkout@v4.1.5
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push [1.21]
        uses: docker/build-push-action@v5
        with:
          context: ./1.21
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx:1.21
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build and push [1.22]
        uses: docker/build-push-action@v5
        with:
          context: ./1.22
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx:1.22
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build and push [1.23]
        uses: docker/build-push-action@v5
        with:
          context: ./1.23
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx:1.23
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build and push [1.24]
        uses: docker/build-push-action@v5
        with:
          context: ./1.24
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx:1.24
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build and push [1.25, latest]
        uses: docker/build-push-action@v5
        with:
          context: ./1.25
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx:1.25,${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      # Docker Hub Personal Access Tokens cannot be used as they are not supported by the API.
      # Unfortunately, this means that enabling 2FA on Docker Hub will prevent the action from working.
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/nginx
          short-description: ${{ github.event.repository.description }}
